	public class PopulatedArray {
	    public static void main(String[] args){
	        //Array Definition: 'int[] lottoNumbers'
        //Array Declaration: 'int[] lottoNumbers = {}'
        //Populating the Array: 'int[] lottoNumbers = {12,56,77,88,99}'
        String[] vinNums = {"1266","5677","7788","8888","9911"};
        
        //Access element at index 2
        System.out.println(vinNums[2]);        
    }
    
}
